try CI with symfony template

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,26 +1,74 @@
-name: CI
+# See: https://github.com/shivammathur/setup-php/blob/master/examples/symfony-mysql.yml
 
-on:
-  push:
-    branches:
-      - main
-  pull_request:
-    branches:
-      - main
+name: CI
+on: [push, pull_request]
+
+#jobs:
+#  ci:
+#    runs-on: ubuntu-latest
+#    steps:
+#      - name: Setup PHP with PECL extension
+#        uses: shivammathur/setup-php@v2
+#        with:
+#          php-version: '8.0'
+#          tools: composer:v2, php-cs-fixer, phpstan, phpunit
+#      - uses: actions/checkout@v2
+##       - name: Run tests
+##         run: make setup && make fixtures && make phpunit
+#      - name: Run PHPStan
+#        run: phpstan analyse src tests
+#      - name: Run CS fixer
+#        run: tools/php-cs-fixer/vendor/bin/php-cs-fixer fix --dry-run
+
 
 jobs:
-  ci:
+  symfony:
+    name: Symfony
     runs-on: ubuntu-latest
+    services:
+      mysql:
+        image: mysql:5.7
+        env:
+          MYSQL_ALLOW_EMPTY_PASSWORD: false
+          MYSQL_ROOT_PASSWORD: root
+          MYSQL_DATABASE: GoStyle_test
+          MYSQL_USERNAME: gostyle
+          MYSQL_PASSWORD: gostyle
+        ports:
+          - 3306/tcp
+        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
     steps:
-      - name: Setup PHP with PECL extension
-        uses: shivammathur/setup-php@v2
+      - name: Checkout
+        uses: actions/checkout@v2
+      - name: Setup PHP, with composer and extensions
+        uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
         with:
           php-version: '8.0'
-          tools: composer:v2, php-cs-fixer, phpstan
-      - uses: actions/checkout@v2
-#       - name: Run tests
-#         run: make setup && make fixtures && make phpunit
-      - name: Run PHPStan
-        run: vendor/bin/phpstan analyse src tests
-      - name: Run CS fixer
-        run: tools/php-cs-fixer/vendor/bin/php-cs-fixer fix --dry-run
+          extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, mysql
+          coverage: xdebug #optional
+      - name: Start mysql service
+        run: sudo /etc/init.d/mysql start
+      - name: Get composer cache directory
+        id: composer-cache
+        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
+      - name: Cache composer dependencies
+        uses: actions/cache@v2
+        with:
+          path: ${{ steps.composer-cache.outputs.dir }}
+          # Use composer.json for key, if composer.lock is not committed.
+          # key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
+          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
+          restore-keys: ${{ runner.os }}-composer-
+      - name: Install Composer dependencies
+        run: |
+          composer require --dev symfony/orm-pack symfony/phpunit-bridge
+          composer install --no-progress --prefer-dist --optimize-autoloader
+          php bin/phpunit install
+      - name: Run Migration
+        run: |
+          php bin/console doctrine:schema:update --force || echo "No migrations found or schema update failed"
+          php bin/console doctrine:migrations:migrate || echo "No migrations found or migration failed"
+        env:
+          DATABASE_URL: mysql://root:root@127.0.0.1:${{ job.services.mysql.ports['3306'] }}/GoStyle_test
+      - name: Run Tests
+        run: php bin/phpunit --coverage-text
